name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore    
