name: ZiggyWallet_CICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_ziggywallet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      working-directory: ./ZiggyWalletCICD/
      run: dotnet restore
    - name: Build
      working-directory: ./ZiggyWalletCICD/
      run: dotnet build --no-restore    
    - name: Test
      working-directory: ./ZiggyWalletCICD/
      run: dotnet test --no-build --verbosity normal
    
